# Generated by Django 6.0.4 on 2026-05-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('durartion', models.TimeField()),
                ('isfavourite', models.BooleanField()),
                ('album_image', models.ImageField(upload_to='image/')),
                ('album_song', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
