# Generated by Django 6.0.4 on 2026-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_image',
        ),
        migrations.AlterField(
            model_name='song',
            name='durartion',
            field=models.DurationField(),
        ),
    ]
