# Generated by Django 6.0.4 on 2026-05-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_song_album_image_alter_song_durartion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='isfavourite',
            field=models.BooleanField(default=False),
        ),
    ]
