# Generated by Django 6.0.4 on 2026-05-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_song_isfavourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='durartion',
            new_name='duration',
        ),
    ]
