# Generated by Django 6.0.4 on 2026-05-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
